### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ansnoussi** [bep/s3deploy#283]
It looks like the latest release [v2.8.0](https://github.com/bep/s3deploy/compare/v2.7.0...v2.8.0) somehow broke s3deploy on a pipeline we have on circleci with the following error : 
```bash
s3deploy v2, commit none, built at unknown
iframe.html (ETag) ↑ panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8b65cc]

goroutine 6 [running]:
github.com/bep/s3deploy/v2/lib.(*osFile).ACL(0xc0002da510, 0xc0004f4060, 0xc000381000)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/files.go:130 +0xc
github.com/bep/s3deploy/v2/lib.(*s3Store).Put(0xc0000d07d0, 0xaddf58, 0xc0000c5040, 0xae0408, 0xc0002da510, 0xc000402018, 0x1, 0x1, 0x0, 0xc000114e88)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/s3.go:88 +0x6d
github.com/bep/s3deploy/v2/lib.(*store).Put(0xc00018f400, 0xaddf58, 0xc0000c5040, 0xae0408, 0xc0002da510, 0xc000402018, 0x1, 0x1, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/store.go:66 +0xe7
github.com/bep/s3deploy/v2/lib.(*Deployer).upload(0xc00030e0e0, 0xaddf58, 0xc0000c5040, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/deployer.go:317 +0x1a6
github.com/bep/s3deploy/v2/lib.Deploy.func2(0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/deployer.go:112 +0x3f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002de750, 0xc00000e3a8)
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f/errgroup/errgroup.go:58 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f/errgroup/errgroup.go:55 +0x66

Exited with code exit status 2
CircleCI received exit code 2
```

We don't have any special config when it comes to s3deploy arguments : 
```bash
s3deploy -source=storybook-static/ -region=$AWS_REGION -key=$AWS_ACCESS_KEY_ID -secret=$AWS_SECRET_ACCESS_KEY -distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID -bucket=$AWS_BUCKET_NAME
```

Currently we downgraded to [v2.7.0](https://github.com/bep/s3deploy/releases/tag/v2.7.0) and the pipeline is back, not sure exactly what causes the problem is the newer version.

**Comment by bep** [comment]
Hmm, sorry about this. I did a test deploy with one of my sites and that worked fine.

/cc @satotake
